basePath: /
host: localhost:8080
info:
  contact: {}
  description: Production-style Go backend for learning debugging and incidents.
  title: Go Testing App API
  version: "1.0"
paths: {}
swagger: "2.0"
